executable      = $ENV(CMSSW_BASE)/src/CMGTools/NanoProc/python/plotter/susy-sos/scripts/runPlotting.sh
output          = $ENV(CMSSW_BASE)/src/CMGTools/NanoProc/python/plotter/susy-sos/scripts/plotting_logs/job.$(ClusterId).$(ProcId).out
error           = $ENV(CMSSW_BASE)/src/CMGTools/NanoProc/python/plotter/susy-sos/scripts/plotting_logs/job.$(ClusterId).$(ProcId).err
log             = $ENV(CMSSW_BASE)/src/CMGTools/NanoProc/python/plotter/susy-sos/scripts/plotting_logs/job.$(ClusterId).$(ProcId).log
getenv = True
+JobFlavour	= "longlunch"
queue arguments from (
# @ needed to separate 'sos_plots.py' and 'mcPlots.py' flags. 
#
######
# 2016 -- 2l -- SRs
#/full/path/to/your/output/directory 2016 2los sr       low   --fakes dd     --signal --data @
#/full/path/to/your/output/directory 2016 2los sr       med   --fakes semidd --signal --data @
#/full/path/to/your/output/directory 2016 2los sr       high  --fakes semidd --signal --data @
#/full/path/to/your/output/directory 2016 2los sr       ultra --fakes semidd --signal --data @
#/full/path/to/your/output/directory 2016 2los sr_col   low   --fakes dd     --signal --data @
#/full/path/to/your/output/directory 2016 2los sr_col   med   --fakes semidd --signal --data @
#/full/path/to/your/output/directory 2016 2los sr_col   high  --fakes semidd --signal --data @
#/full/path/to/your/output/directory 2016 2los sr_col   ultra --fakes semidd --signal --data @
# 2016 -- 2l -- CRs
#/full/path/to/your/output/directory 2016 2los cr_dy    low   --fakes dd     --signal --data @ 
#/full/path/to/your/output/directory 2016 2los cr_dy    med   --fakes dd     --signal --data @ 
#/full/path/to/your/output/directory 2016 2los cr_tt    low   --fakes dd     --signal --data @ 
#/full/path/to/your/output/directory 2016 2los cr_tt    med   --fakes dd     --signal --data @ 
#/full/path/to/your/output/directory 2016 2los cr_vv    low   --fakes dd     --signal --data @
#/full/path/to/your/output/directory 2016 2los cr_vv    med   --fakes dd     --signal --data @
#/full/path/to/your/output/directory 2016 2los cr_ss    med   --fakes semidd --signal --data @
# 2016 -- 2l -- ARs
#/full/path/to/your/output/directory 2016 2los appl     low   --fakes mc              --data @
#/full/path/to/your/output/directory 2016 2los appl     med   --fakes mc              --data @
#/full/path/to/your/output/directory 2016 2los appl     high  --fakes mc              --data @
#/full/path/to/your/output/directory 2016 2los appl     ultra --fakes mc              --data @
#/full/path/to/your/output/directory 2016 2los appl_col low   --fakes mc              --data @
#/full/path/to/your/output/directory 2016 2los appl_col med   --fakes mc              --data @
#/full/path/to/your/output/directory 2016 2los appl_col high  --fakes mc              --data @
#/full/path/to/your/output/directory 2016 2los appl_col ultra --fakes mc              --data @
# 2016 -- 3l -- SRs
#/full/path/to/your/output/directory 2016 3l   sr      low    --fakes semidd --signal --data @
#/full/path/to/your/output/directory 2016 3l   sr      med    --fakes semidd --signal --data @
# 2016 -- 3l -- CRs
#/full/path/to/your/output/directory 2016 3l   cr_wz   low    --fakes dd     --signal --data @ 
#/full/path/to/your/output/directory 2016 3l   cr_wz   med    --fakes dd     --signal --data @ 
# 2016 -- 3l -- ARs
#/full/path/to/your/output/directory 2016 3l   appl    low    --fakes mc              --data @ 
#/full/path/to/your/output/directory 2016 3l   appl    med    --fakes mc              --data @ 
#
######
# 2017 -- 2l -- SRs
#/full/path/to/your/output/directory 2017 2los sr       low   --fakes dd     --signal --data @
#/full/path/to/your/output/directory 2017 2los sr       med   --fakes semidd --signal --data @
#/full/path/to/your/output/directory 2017 2los sr       high  --fakes semidd --signal --data @
#/full/path/to/your/output/directory 2017 2los sr       ultra --fakes semidd --signal --data @
#/full/path/to/your/output/directory 2017 2los sr_col   low   --fakes dd     --signal --data @
#/full/path/to/your/output/directory 2017 2los sr_col   med   --fakes semidd --signal --data @
#/full/path/to/your/output/directory 2017 2los sr_col   high  --fakes semidd --signal --data @
#/full/path/to/your/output/directory 2017 2los sr_col   ultra --fakes semidd --signal --data @
# 2017 -- 2l -- CRs
#/full/path/to/your/output/directory 2017 2los cr_dy    low   --fakes dd     --signal --data @
#/full/path/to/your/output/directory 2017 2los cr_dy    med   --fakes dd     --signal --data @
#/full/path/to/your/output/directory 2017 2los cr_tt    low   --fakes dd     --signal --data @
#/full/path/to/your/output/directory 2017 2los cr_tt    med   --fakes dd     --signal --data @
#/full/path/to/your/output/directory 2017 2los cr_vv    low   --fakes dd     --signal --data @
#/full/path/to/your/output/directory 2017 2los cr_vv    med   --fakes dd     --signal --data @
#/full/path/to/your/output/directory 2017 2los cr_ss    med   --fakes semidd --signal --data @
# 2017 -- 2l -- ARs
#/full/path/to/your/output/directory 2017 2los appl     low   --fakes mc              --data @
#/full/path/to/your/output/directory 2017 2los appl     med   --fakes mc              --data @
#/full/path/to/your/output/directory 2017 2los appl     high  --fakes mc              --data @
#/full/path/to/your/output/directory 2017 2los appl     ultra --fakes mc              --data @
#/full/path/to/your/output/directory 2017 2los appl_col low   --fakes mc              --data @
#/full/path/to/your/output/directory 2017 2los appl_col med   --fakes mc              --data @
#/full/path/to/your/output/directory 2017 2los appl_col high  --fakes mc              --data @
#/full/path/to/your/output/directory 2017 2los appl_col ultra --fakes mc              --data @
# 2017 -- 3l -- SRs
#/full/path/to/your/output/directory 2017 3l    sr      low   --fakes semidd --signal --data @
#/full/path/to/your/output/directory 2017 3l    sr      med   --fakes semidd --signal --data @
# 2017 -- 3l -- CRs
#/full/path/to/your/output/directory 2017 3l    cr_wz   low   --fakes dd     --signal --data @
#/full/path/to/your/output/directory 2017 3l    cr_wz   med   --fakes dd     --signal --data @
# 2017 -- 3l -- ARs
#/full/path/to/your/output/directory 2017 3l    appl    low   --fakes mc              --data @
#/full/path/to/your/output/directory 2017 3l    appl    med   --fakes mc              --data @
#
######
# 2018 -- 2l -- SRs
#/full/path/to/your/output/directory 2018 2los sr       low   --fakes dd     --signal --data @
#/full/path/to/your/output/directory 2018 2los sr       med   --fakes semidd --signal --data @
#/full/path/to/your/output/directory 2018 2los sr       high  --fakes semidd --signal --data @
#/full/path/to/your/output/directory 2018 2los sr       ultra --fakes semidd --signal --data @
#/full/path/to/your/output/directory 2018 2los sr_col   low   --fakes dd     --signal --data @
#/full/path/to/your/output/directory 2018 2los sr_col   med   --fakes semidd --signal --data @
#/full/path/to/your/output/directory 2018 2los sr_col   high  --fakes semidd --signal --data @
#/full/path/to/your/output/directory 2018 2los sr_col   ultra --fakes semidd --signal --data @
# 2018 -- 2l -- CRs
#/full/path/to/your/output/directory 2018 2los cr_dy    low   --fakes dd     --signal --data @
#/full/path/to/your/output/directory 2018 2los cr_dy    med   --fakes dd     --signal --data @
#/full/path/to/your/output/directory 2018 2los cr_tt    low   --fakes dd     --signal --data @
#/full/path/to/your/output/directory 2018 2los cr_tt    med   --fakes dd     --signal --data @
#/full/path/to/your/output/directory 2018 2los cr_vv    low   --fakes dd     --signal --data @
#/full/path/to/your/output/directory 2018 2los cr_vv    med   --fakes dd     --signal --data @
#/full/path/to/your/output/directory 2018 2los cr_ss    med   --fakes semidd --signal --data @
# 2018 -- 2l -- ARs
#/full/path/to/your/output/directory 2018 2los appl     low   --fakes mc              --data @
#/full/path/to/your/output/directory 2018 2los appl     med   --fakes mc              --data @
#/full/path/to/your/output/directory 2018 2los appl     high  --fakes mc              --data @
#/full/path/to/your/output/directory 2018 2los appl     ultra --fakes mc              --data @
#/full/path/to/your/output/directory 2018 2los appl_col low   --fakes mc              --data @
#/full/path/to/your/output/directory 2018 2los appl_col med   --fakes mc              --data @
#/full/path/to/your/output/directory 2018 2los appl_col high  --fakes mc              --data @
#/full/path/to/your/output/directory 2018 2los appl_col ultra --fakes mc              --data @
# 2018 -- 3l -- SRs
#/full/path/to/your/output/directory 2018 3l   sr       low   --fakes semidd --signal --data @
#/full/path/to/your/output/directory 2018 3l   sr       med   --fakes semidd --signal --data @
# 2018 -- 3l -- CRs
#/full/path/to/your/output/directory 2018 3l   cr_wz    low   --fakes dd     --signal --data @ 
#/full/path/to/your/output/directory 2018 3l   cr_wz    med   --fakes dd     --signal --data @ 
# 2018 -- 3l -- ARs
#/full/path/to/your/output/directory 2018 3l   appl     low   --fakes mc              --data @
#/full/path/to/your/output/directory 2018 3l   appl     med   --fakes mc              --data @
)
